[package]
name = "pixterm"
version = "0.1.0"
edition = "2021"
# author = "RubixDev"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansipix = "0.1.0"
structopt = "0.3.25"
